const ActionTypes = {
	CHANGE_SEARCHFIELD: 'CHANGE_SEARCHFIELD',
	REQUEST_ROBOTS_START: 'REQUEST_ROBOTS_START',
	REQUEST_ROBOTS_SUCCESS: 'REQUEST_ROBOTS_SUCCESS',
	REQUEST_ROBOTS_FAILURE: 'REQUEST_ROBOTS_FAILURE'
};

export default ActionTypes;